# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin/Desktop/Projects/C++/Rubix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin/Desktop/Projects/C++/Rubix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@echo "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/Desktop/Projects/C++/Rubix/CMakeFiles /home/kevin/Desktop/Projects/C++/Rubix/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/Desktop/Projects/C++/Rubix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Rubix.bc

# Build rule for target.
Rubix.bc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Rubix.bc
.PHONY : Rubix.bc

# fast build rule for target.
Rubix.bc/fast:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/build
.PHONY : Rubix.bc/fast

home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.o: home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.i: home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.s: home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.o: home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.i: home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.s: home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.o: home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.i: home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.s: home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.o: home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.i: home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.s: home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.o: home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.i: home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.s: home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.o: home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.i: home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.s: home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.cpp.s

home/kevin/Desktop/Projects/C++/KTEngine/src/Window.o: home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Window.o

# target to build an object file
home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.o
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.o

home/kevin/Desktop/Projects/C++/KTEngine/src/Window.i: home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Window.i

# target to preprocess a source file
home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.i
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.i

home/kevin/Desktop/Projects/C++/KTEngine/src/Window.s: home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Window.s

# target to generate assembly for a file
home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.s
.PHONY : home/kevin/Desktop/Projects/C++/KTEngine/src/Window.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Rubix.bc.dir/build.make CMakeFiles/Rubix.bc.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Rubix.bc"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_reader.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_value.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/external/jsoncpp/src/lib_json/json_writer.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/GameEngine.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/GameObject.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Font.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/GameSprite.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Geometries.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Quad.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/ShaderManager.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/SpriteTechnique.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Text.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/TextTechnique.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Graphics/Texture.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/IGameScene.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/AnimationSystem.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Systems/RenderSystem.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Utility/Time.s"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Window.o"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Window.i"
	@echo "... home/kevin/Desktop/Projects/C++/KTEngine/src/Window.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

